### ISSUE TITLE
05 Create a detailed page and render a detailed characters card

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/next-and-morty#5]
When clicking on the `Show more` button, the user should be navigated to a detailed characters page. The characters card here has a button where the user can display even more details.
            <img width="417" alt="Bildschirmfoto 2022-04-02 um 20 05 05" src="https://user-images.githubusercontent.com/54703643/161395733-03d81283-b947-45b1-b57b-f33349b32181.png">
## ToDos
- [x] move this issue in the board from `ToDo` tab into `In Progress` tab
- [x] create a new branch locally
- [x] create character page (you will need to create dynamic routes. Check out [the next dynamic-routes docs](https://nextjs.org/docs/routing/dynamic-routes))
- [x] create a detailed character card which shows more info like species, gender, status (check the API for more content)
- [x] create logic, when clicking the „show more“ button on the `start page`, the user is moved to the detailed page and the character is loaded with more details
- [x] commit everything
- [x] push everything to the remote repo on GitHub
- [x] create a `pull request`
- [x] write a meaningful pr message that contains what happened in the `pull request`
- [ ] ask for a review from your colleagues
- [ ] after review merge into main
- [ ] move this issue in the board from `In Progress` tab into `Done` tab
- [ ] close this issue
